version: '3.7'
services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - rbi-services
      
      
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: googletest
      MYSQL_USER: google
      MYSQL_PASSWORD: googletest
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - D:\MYSQL:/var/lib/mysql
    networks:
      - rbi-services         

  eureka-service:
    image: netflix-eureka-naming-server:0.0.2-SNAPSHOT
    ports:
      - "8761:8761"
    restart: always
    networks:
      - rbi-services


  zuul-api-gateway:
    image: netflix-zuul-api-gateway-server:0.0.2-SNAPSHOT
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:
      - "8765:8765"
    restart: always
    depends_on:
      - eureka-service
      - rabbitmq
    networks:
      - rbi-services
      
 

  config-service:
    image: config-server:v1.0
    environment:
      RDS_HOSTNAME: mysql
    ports:
      - "8012:8012"
    restart: always
    depends_on:
      - eureka-service
      - rabbitmq
      - mysql
    networks:
      - rbi-services


  master-service:
    image: master-service:v1.1
    environment:
      CONFIG_SERVER: config-service
      RDS_HOSTNAME: mysql
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - eureka-service
      - rabbitmq
      - mysql
      - config-service
      - zuul-api-gateway
    networks:
      - rbi-services
      
      
  entity-service:
    image: entity-service:v1.0
    environment:
      CONFIG_SERVER: config-service
      RDS_HOSTNAME: mysql
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - eureka-service
      - rabbitmq
      - mysql
      - config-service
      - zuul-api-gateway
    networks:
      - rbi-services      
 
  
# Networks to be created to facilitate communication between containers
networks:
  rbi-services: